src/main/java/com/cgi/osd/transactiondemo/logic/BookingServiceBean.java
package com.cgi.osd.transactiondemo.logic;

import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import java.util.Set;
import java.util.logging.Logger;

import javax.ejb.Lock;
import javax.ejb.LockType;
import javax.ejb.Singleton;
import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.inject.Inject;

import com.cgi.osd.transactiondemo.logic.domainobject.CustomerDO;
import com.cgi.osd.transactiondemo.logic.domainobject.LockStrategy;
import com.cgi.osd.transactiondemo.logic.domainobject.SeatDO;
import com.cgi.osd.transactiondemo.logic.exception.SeatBookedException;
import com.cgi.osd.transactiondemo.persistence.PersistenceManager;

/**
 * This class is responsible for implementing the booking services, which means implementing the main business logic for
 * the system.
 *
 */
@Singleton
@TransactionAttribute(TransactionAttributeType.NEVER)
public class BookingServiceBean extends Observable implements BookingService {

	@Inject
	private Logger logger;
	@Inject
	private PersistenceManager persistenceManager;

	@Override
	public void cancelBookings(Collection<SeatDO> seats) {
		throw new RuntimeException("Not yet implemented.");
	}

	@Override
	@TransactionAttribute(TransactionAttributeType.NOT_SUPPORTED)
	public void createBookings(CustomerDO customer, Collection<SeatDO> seats) throws SeatBookedException {
		final Set<SeatDO> bookedSeats = new HashSet<>();
		for (final SeatDO seat : seats) {
			if (seat != null && !seat.isBooked()) {
				bookedSeats.add(seat);
			}
		}
		if (!bookedSeats.isEmpty()) {
			this.persistenceManager.createBookings(customer, bookedSeats);
		}
		sendNotification(seats.size());
	}

	@Override
	public List<SeatDO> getAllSeats() {
		throw new RuntimeException("Not yet implemented.");
	}

	@Override
	public List<SeatDO> getBookedSeats() {
		throw new RuntimeException("Not yet implemented.");
	}

	@Override
	public CustomerDO getCustomerFromEmail(String email) {
		final CustomerDO customer = this.persistenceManager.getCustomer(email);
		return customer;
	}

	@TransactionAttribute(TransactionAttributeType.NOT_SUPPORTED)
	@Override
	public List<SeatDO> getCustomersAndFreeSeat(CustomerDO customer) {
		List<SeatDO> seats;
		if (customer == null || getCustomerFromEmail(customer.getEmail()) == null) {
			seats = this.persistenceManager.getFreeSeats();
		} else {
			seats = this.persistenceManager.getCustomerSeats(customer);
		}
		return seats;
	}

	@Override
	public List<SeatDO> getFreeSeats() {
		final List<SeatDO> seats = this.persistenceManager.getFreeSeats();
		return seats;
	}

	@Override
	public LockStrategy getLockStrategy() {
		return this.persistenceManager.getLockStrategy();
	}

	@Override
	@TransactionAttribute(TransactionAttributeType.NOT_SUPPORTED)
	public void lockSeat(SeatDO seat, CustomerDO customer, boolean lock) throws SeatBookedException {
		this.persistenceManager.lockSeat(seat, customer, lock);
		if (getLockStrategy() == LockStrategy.PESSIMISTIC) {
			sendNotification(1);
		}
	}

	@Override
	@Lock(LockType.WRITE)
	@TransactionAttribute(TransactionAttributeType.NOT_SUPPORTED)
	public void registerObserver(Observer observer) {
		super.addObserver(observer);
		this.logger.fine("Observer registered.");
	}

	@Override
	public void releaseSeats(CustomerDO customer, Collection<SeatDO> seats) throws SeatBookedException {
		for (final SeatDO seat : seats) {
			this.persistenceManager.lockSeat(seat, customer, false);
		}
		sendNotification(seats.size());
	}

	@Override
	public void sendNotification(int numberOfSeats) {
		super.setChanged();
		super.notifyObservers(new Integer(numberOfSeats));
		super.clearChanged();
	}

	@Override
	public void setLockStrategy(LockStrategy lockStrategy) {
		this.persistenceManager.setLockStrategy(lockStrategy);
	}

	@Override
	@Lock(LockType.WRITE)
	@TransactionAttribute(TransactionAttributeType.REQUIRED)
	public void unregisterObserver(Observer observer) {
		super.deleteObserver(observer);
		this.logger.fine("Observer unregistered.");
	}

}

src/main/java/com/cgi/osd/transactiondemo/persistence/LockTrackerBean.java
package com.cgi.osd.transactiondemo.persistence;

import javax.annotation.PostConstruct;
import javax.ejb.ConcurrencyManagement;
import javax.ejb.ConcurrencyManagementType;
import javax.ejb.Lock;
import javax.ejb.LockType;
import javax.ejb.Singleton;
import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;

import com.cgi.osd.transactiondemo.logic.domainobject.LockStrategy;

/**
 * This class is responsible for keeping locking information as versions for
 * optimistic strategy and the selected strategy itself.
 *
 * @author anderssonhr
 *
 */
@Singleton
@ConcurrencyManagement(ConcurrencyManagementType.CONTAINER)
@TransactionAttribute(TransactionAttributeType.NOT_SUPPORTED)
@Lock(LockType.READ)
public class LockTrackerBean implements LockTracker {

    private LockStrategy lockStrategy;

    /*
     * (non-Javadoc)
     *
     * @see
     * com.cgi.osd.transactiondemo.persistence.LockTracker#getLockStrategy()
     */
    @Override
    public LockStrategy getLockStrategy() {
	return this.lockStrategy;
    }

    /*
     * (non-Javadoc)
     *
     * @see
     * com.cgi.osd.transactiondemo.persistence.LockTracker#setLockStrategy(com.
     * cgi.osd.transactiondemo.persistence.LockTrackerBean.LockStrategy )
     */
    @Override
    @Lock(LockType.WRITE)
    public void setLockStrategy(LockStrategy lockStrategy) {
	this.lockStrategy = lockStrategy;
    }

    @PostConstruct
    private void init() {
	final String systemDefaultLock = System.getProperty("default-lock");
	if (systemDefaultLock != null && "pessimistic".equalsIgnoreCase(systemDefaultLock)) {
	    this.lockStrategy = LockStrategy.PESSIMISTIC;
	} else {
	    this.lockStrategy = LockStrategy.OPTIMISTIC;
	}
    }

}

src/main/java/com/cgi/osd/transactiondemo/presentation/gui/BookingController.java
package com.cgi.osd.transactiondemo.presentation.gui;

import java.io.Serializable;
import java.util.Collection;
import java.util.Collections;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Logger;

import javax.annotation.PreDestroy;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.application.ViewExpiredException;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.faces.event.ValueChangeEvent;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.component.datatable.DataTable;

import com.cgi.osd.transactiondemo.logic.BookingService;
import com.cgi.osd.transactiondemo.logic.domainobject.CustomerDO;
import com.cgi.osd.transactiondemo.logic.domainobject.SeatDO;
import com.cgi.osd.transactiondemo.logic.exception.SeatBookedException;

/**
 * This class is responsible for the controller part of the MVC pattern for the booking process.
 *
 */
@SessionScoped
@Named
public class BookingController implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private Logger logger;

	@Inject
	private FacesContext facesContext;

	@Inject
	private BookingData bookingData;

	@Inject
	private BookingService bookingService;

	@Inject
	private PushController pushController;

	public void confirmBookings(ActionEvent ev) {
		try {
			final CustomerDO customer = this.bookingData.getCustomer();
			this.bookingData.setCustomer(customer);
			final Set<SeatDO> seatsToBook = this.bookingData.getSeatsToBook();
			this.bookingService.createBookings(customer, seatsToBook);
			this.bookingData.updateSeats();
			this.bookingData.clearSeatsToBook();
		} catch (final SeatBookedException e) {
			this.facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Bokning misslyckades!",
					"Plats bokad av annan kund."));
		}
	}

	public String getEmail() {
		if (this.bookingData.getCustomer() == null) {
			return "";
		}
		return this.bookingData.getCustomer().getEmail();
	}

	public String getFirstName() {
		if (this.bookingData.getCustomer() == null) {
			return "";
		}
		return this.bookingData.getCustomer().getFirstName();
	}

	public String getLastName() {
		if (this.bookingData.getCustomer() == null) {
			return "";
		}
		return this.bookingData.getCustomer().getLastName();
	}

	public List<SeatSelection> getSeatSelects() {
		Map<Integer, SeatSelection> response = this.bookingData.getSeatSelections();
		if (response.isEmpty()) {
			updateSeatsFromDb();
			response = this.bookingData.getSeatSelections();
		}
		final Collection<SeatSelection> values = response.values();
		final List<SeatSelection> result = new LinkedList<>(values);
		Collections.sort(result);
		return result;
	}

	public String getTelephoneNumber() {
		if (this.bookingData.getCustomer() == null) {
			return "";
		}
		return this.bookingData.getCustomer().getTelephoneNumber();
	}

	public boolean isCustomerEntered() {
		final CustomerDO customer = this.bookingData.getCustomer();
		if (customer == null) {
			return false;
		}
		return customer.isMandatorySet();
	}

	public void onEmailChanged(ValueChangeEvent ev) {
		final String email = (String) ev.getNewValue();
		this.bookingData.fetchOrCreateCustomer(email);
		updateSeatsFromDb();
	}

	public void onSelectionChanged(ValueChangeEvent ev) {
		try {
			this.logger.fine("Lock button pressed.");
			final UIComponent component = ev.getComponent();

			final DataTable table = (DataTable) component.getParent().getParent();
			final Boolean newBookingStatus = (Boolean) ev.getNewValue();
			final SeatSelection seatSelect = (SeatSelection) table.getRowData();
			final SeatDO selectedSeat = seatSelect.getSeat();
			final Integer seatNumber = selectedSeat.getSeatNumber();
			final boolean selected = newBookingStatus.booleanValue();

			this.bookingData.setSelected(seatNumber, selected);
			this.bookingService.lockSeat(selectedSeat, this.bookingData.getCustomer(), selected);

			this.logger.fine("Lock changed to " + newBookingStatus.toString() + " on seat number "
					+ selectedSeat.getSeatNumber());
		} catch (final SeatBookedException e) {
			this.facesContext.addMessage("bookingMessage", new FacesMessage(FacesMessage.SEVERITY_WARN,
					"Bokning misslyckades!", "Plats bokad av annan kund."));
			this.pushController.updateSeatTables();
		}
	}

	public void setEmail(String email) {
		// Email is taken care of in onEmailChanged.
	}

	public void setFirstName(String firstName) {
		this.bookingData.getCustomer().setFirstName(firstName);
	}

	public void setLastName(String lastName) {
		this.bookingData.getCustomer().setLastName(lastName);
	}

	public void setTelephoneNumber(String telephoneNumber) {
		this.bookingData.getCustomer().setTelephoneNumber(telephoneNumber);
	}

	/**
	 * This method is for test purposes only.
	 */
	public void throwViewExpiredException() {
		throw new ViewExpiredException("A ViewExpiredException!",
				FacesContext.getCurrentInstance().getViewRoot().getViewId());
	}

	/**
	 * This method updates the seat data for the web GUI.
	 */
	public void updateSeatsFromDb() {
		this.logger.fine("updateSeatsFromDb called.");
		this.bookingData.updateSeats();
		this.logger.fine("updateSeatsFromDb ready.");
	}

	@PreDestroy
	private void onSessionTimeout() {
		final CustomerDO customer = this.bookingData.getCustomer();
		if (customer != null) {
			try {
				final Collection<SeatDO> seatsToRelease = this.bookingData.getSeatsToBook();
				this.bookingService.releaseSeats(customer, seatsToRelease);
				this.logger.fine("Session time out");
			} catch (final SeatBookedException e) {
				this.logger.warning("Failed to release customer's locks at session timeout.");
			}
		}
	}

}

src/main/java/com/cgi/osd/transactiondemo/presentation/gui/ChatController.java
/**
 *
 */
package com.cgi.osd.transactiondemo.presentation.gui;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import org.primefaces.push.EventBus;
import org.primefaces.push.EventBusFactory;

/**
 * This class is responsible for the controller part of the MVC pattern applied to the chat process.
 *
 * @author anderssonhr
 *
 */
@SessionScoped
@Named
public class ChatController implements Serializable {

    private static final long serialVersionUID = 1L;
    private EventBus eventBus;
    private String textInput;

    public String getTextInput() {
	return this.textInput;
    }

    public void sendMessageToClient() {
	if (this.textInput != null || !this.textInput.isEmpty()) {
	    this.eventBus.publish("/chat", this.textInput);
	}
    }

    public void setTextInput(String textInput) {
	this.textInput = textInput;
    }

    @PostConstruct
    private void init() {
	this.eventBus = EventBusFactory.getDefault().eventBus();
    }

}

src/main/java/com/cgi/osd/transactiondemo/presentation/gui/PushController.java
package com.cgi.osd.transactiondemo.presentation.gui;

/**
 * This interface defines the public methods of the Push controller.
 *
 * @author anderssonhr
 *
 */
public interface PushController {

    /**
     * This method is used for getting information about push status.
     *
     * @return true is push is disabled.
     */
    public boolean isPushDisabled();

    /**
     * This method sets the push status.
     *
     * @param pushDisabled
     *            true if push should be disabled.
     */
    public void setPushDisabled(boolean pushDisabled);

    /**
     * This method pushes an event to the clients that causes them to update their seat tables. The push is performed regardless of push
     * disable status.
     */
    public void updateSeatTables();
}

src/main/java/com/cgi/osd/transactiondemo/presentation/gui/PushControllerBean.java
package com.cgi.osd.transactiondemo.presentation.gui;

import java.util.Observable;
import java.util.Observer;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.ejb.ConcurrencyManagement;
import javax.ejb.ConcurrencyManagementType;
import javax.ejb.DependsOn;
import javax.ejb.Lock;
import javax.ejb.LockType;
import javax.ejb.Singleton;
import javax.ejb.Startup;
import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.inject.Inject;

import org.primefaces.push.EventBus;
import org.primefaces.push.EventBusFactory;

import com.cgi.osd.transactiondemo.logic.BookingService;

/**
 * This class is responsible for creating push events when notified about booking changes.
 *
 * @author anderssonhr
 *
 */
@Singleton
@Startup
@DependsOn("BookingServiceBean")
@ConcurrencyManagement(ConcurrencyManagementType.CONTAINER)
@TransactionAttribute(TransactionAttributeType.NEVER)
@Lock(LockType.READ)
public class PushControllerBean implements Observer, PushController {

    private boolean pushDisabled;
    private EventBus eventBus;

    @Inject
    private Logger logger;

    @Inject
    private BookingService bookingService;

    @Override
    public boolean isPushDisabled() {
	return pushDisabled;
    }

    @Override
    @Lock(LockType.WRITE)
    public void setPushDisabled(boolean pushDisabled) {
	this.pushDisabled = pushDisabled;
    }

    @Override
    public void update(Observable o, Object arg) {
	if (pushDisabled) {
	    return;
	}
	final Integer numberOfSeats = (Integer) arg;
	performPush(numberOfSeats);
    }

    @Override
    public void updateSeatTables() {
	performPush(new Integer(0));
    }

    @PostConstruct
    private void init() {
	bookingService.registerObserver(this);
	eventBus = EventBusFactory.getDefault().eventBus();
    }

    @PreDestroy
    private void onDestroy() {
	bookingService.unregisterObserver(this);
    }

    private void performPush(Integer numberOfSeats) {
	eventBus.publish("/seatList", numberOfSeats);
	logger.fine("Push performed.");
    }

}

src/main/java/com/cgi/osd/transactiondemo/presentation/gui/SettingController.java
/**
 *
 */
package com.cgi.osd.transactiondemo.presentation.gui;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.cgi.osd.transactiondemo.logic.BookingService;
import com.cgi.osd.transactiondemo.logic.domainobject.LockStrategy;

/**
 * This class is responsible for the controller part of the MVC pattern applied to the setting process. Note that settings are application
 * global.
 *
 * @author anderssonhr
 *
 */
@RequestScoped
@Named
public class SettingController {

    @Inject
    private PushController pushController;

    @Inject
    private BookingService bookingService;

    public boolean getPushDisabled() {
	final boolean value = this.pushController.isPushDisabled();
	return value;
    }

    public String getStrategy() {
	final LockStrategy lockStrategy = this.bookingService.getLockStrategy();
	String lockStrategyString;
	switch (lockStrategy) {
	case OPTIMISTIC:
	    lockStrategyString = "optimistic";
	    break;
	case PESSIMISTIC:
	    lockStrategyString = "pessimistic";
	    break;
	default:
	    lockStrategyString = "optimistic";
	    break;
	}
	return lockStrategyString;
    }

    public void setPushDisabled(boolean value) {
	this.pushController.setPushDisabled(value);
    }

    public void setStrategy(String strategyString) {
	LockStrategy lockStrategy;
	switch (strategyString) {
	case "optimistic":
	    lockStrategy = LockStrategy.OPTIMISTIC;
	    break;
	case "pessimistic":
	    lockStrategy = LockStrategy.PESSIMISTIC;
	    break;
	default:
	    lockStrategy = LockStrategy.OPTIMISTIC;
	    break;
	}
	this.bookingService.setLockStrategy(lockStrategy);
    }

}

src/main/webapp/booking.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

	<h:form id="seatBookingForm" styleClass="basicform">
		<p:growl widgetVar="growlPush" />
		 
		<p:panelGrid columns="2">
			<p:panel>
				<p:panelGrid columns="2">
					<h:outputText value="E-post" />
					<p:inputText id ="email" value="#{bookingController.email}" required="true"
						valueChangeListener="#{bookingController.onEmailChanged}">
						<p:ajax event="change"
							update="email, firstName, lastName, telephone, bookingTable" />
					</p:inputText>

					<h:outputText value="Förnamn" />
					<p:inputText id="firstName" value="#{bookingController.firstName}" required="true" >
						<p:ajax event="change" update="bookingTable"/>
					</p:inputText>

					<h:outputText value="Efternamn" />
					<p:inputText id="lastName" value="#{bookingController.lastName}" required="true" >
						<p:ajax event="change" update="bookingTable"/>
					</p:inputText>

					<h:outputText value="Telefon" />
					<p:inputText id="telephone" value="#{bookingController.telephoneNumber}" required="false" >
						<p:ajax event="change" />
					</p:inputText>

				</p:panelGrid>
			</p:panel>
			<p:panel>
				<p:dataTable id="bookingTable" var="seatSelects" scrollable="true"
					scrollHeight="393" value="#{bookingController.seatSelects}">
					<p:column headerText="Platsnummer" class="centeredColumn">
						<h:outputText value="#{seatSelects.seat.seatNumber}" />
					</p:column>
					<p:column headerText="Boka" class="centeredColumn">
						<p:selectBooleanButton class="booleanButton" onLabel="ja"
							offLabel="nej" value="#{seatSelects.selected}"
							disabled="#{seatSelects.seat.booked || !bookingController.customerEntered}"
							valueChangeListener="#{bookingController.onSelectionChanged}">
							<p:ajax event="change" update="bookingTable" />
						</p:selectBooleanButton>
					</p:column>
				</p:dataTable>
			</p:panel>
			<f:facet name="footer">
				<p:commandButton value="Bekräfta" icon="ui-icon-check" ajax="false" actionListener="#{bookingController.confirmBookings}" />
				<p:messages id="bookingMessage" showDetail="true" autoUpdate="true" closable="true" />
			</f:facet>
		</p:panelGrid>
		
		<p:ajaxExceptionHandler type="javax.faces.application.ViewExpiredException" onexception="handleSessionExpired();" />
	</h:form>
	

	<p:socket onMessage="handleMessage" channel="/seatList">  
		<p:ajax event="message"
			listener="#{bookingController.updateSeatsFromDb}"
			update="seatBookingForm:bookingTable" />
	</p:socket>

</ui:composition>

src/main/webapp/chat.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui" >

	<h:form id="chatForm" styleClass="basicform">
		<h:panelGrid columns="1" styleClass="settingGrid">
			<p:inputTextarea id = "textOutput" widgetVar="textOutput" rows="10" cols="50" />
			<p:inputText id = "textInput" widgetVar ="textInput" value="#{chatController.textInput}" styleClass="chattInput">
				<p:ajax event="change" update="textInput" />
			</p:inputText>
			<p:commandButton value="Sänd" ajax="true"
				actionListener="#{chatController.sendMessageToClient}" />
		</h:panelGrid>
	</h:form>

	<p:socket channel="/chat" onMessage="handleChat" />


</ui:composition>

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/default.xhtml">
	<ui:define name="content">

		<p:tabView dynamic="true" cache = "false">
			<p:tab title="Boka">
				<ui:include src="/booking.xhtml" />
			</p:tab>
			<p:tab title="Ställ in" >
				<ui:include src="/setting.xhtml" />
			</p:tab>
			<p:tab title="Chatta" >
				<ui:include src="/chat.xhtml" />
			</p:tab>
		</p:tabView>


	</ui:define>
</ui:composition>

src/main/webapp/session-expired.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/default.xhtml">
	<ui:define name="content">

		<p:panelGrid columns="2">
			<h:outputText value="Din pågående bokning har gått ut" />
			<p:button value="Börja om"  outcome="index"/> 
		</p:panelGrid>


	</ui:define>
</ui:composition>

src/main/webapp/setting.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

	<h:form id="settingForm" styleClass="basicform">
		<h:panelGrid columns="2" styleClass="settingGrid">
			<p:outputLabel for="strategy" value="Strategi:" />
			<p:selectOneRadio id="strategy" value="#{settingController.strategy}" layout="grid" columns="2">
				<f:selectItem itemLabel="Optimistic" itemValue="optimistic" />
				<f:selectItem itemLabel="Pessimistic" itemValue="pessimistic" />
				<p:ajax />
			</p:selectOneRadio>
			<p:outputLabel for="disablePush" value="Disable push:" />
			<p:selectBooleanCheckbox id="disablePush" value="#{settingController.pushDisabled}" styleClass="settingCheckbox">
				<p:ajax />
			</p:selectBooleanCheckbox>
		</h:panelGrid>
	</h:form>
</ui:composition>